from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


@dataclass(frozen=True)
class ExternalToolsUI:
    tools_group: Any
    tools_status_hint: Any
    wud2app_version: Any
    wud2app_probe: Any
    wudcompress_version: Any
    wudcompress_probe: Any
    btn_tools_probe: Any
    output_edit: Optional[Any]
    temp_edit: Optional[Any]
    btn_output: Optional[Any]
    btn_temp: Optional[Any]


def build_external_tools_ui(
    QtWidgets,
    DropLineEdit,
    parent_widget: Any,
    tools_layout: Any,
    show_external_tools: bool,
    dnd_enabled: bool,
    on_drop_output,
    on_drop_temp,
) -> ExternalToolsUI:
    tools_group = QtWidgets.QGroupBox("External Tools Status")
    tools_group_layout = QtWidgets.QGridLayout(tools_group)

    wud2app_version = QtWidgets.QLabel("unknown")
    wud2app_probe = QtWidgets.QLabel("probe: pending")
    wudcompress_version = QtWidgets.QLabel("unknown")
    wudcompress_probe = QtWidgets.QLabel("probe: pending")
    btn_tools_probe = QtWidgets.QPushButton("Tools prüfen")

    tools_group_layout.addWidget(QtWidgets.QLabel("wud2app version:"), 0, 0)
    tools_group_layout.addWidget(wud2app_version, 0, 1)
    tools_group_layout.addWidget(QtWidgets.QLabel("wud2app probe:"), 1, 0)
    tools_group_layout.addWidget(wud2app_probe, 1, 1)
    tools_group_layout.addWidget(QtWidgets.QLabel("wudcompress version:"), 2, 0)
    tools_group_layout.addWidget(wudcompress_version, 2, 1)
    tools_group_layout.addWidget(QtWidgets.QLabel("wudcompress probe:"), 3, 0)
    tools_group_layout.addWidget(wudcompress_probe, 3, 1)
    tools_group_layout.addWidget(btn_tools_probe, 4, 0, 1, 2)

    tools_status_hint = QtWidgets.QLabel(
        "Externe Tools werden für spezielle Konvertierungen genutzt. Prüfe den Status bei Bedarf."
    )
    tools_status_hint.setWordWrap(True)

    output_edit = None
    temp_edit = None
    btn_output = None
    btn_temp = None

    if show_external_tools:
        external_form = QtWidgets.QGridLayout()
        external_form.setHorizontalSpacing(10)
        external_form.setVerticalSpacing(6)
        tools_layout.addLayout(external_form)

        tools_intro = QtWidgets.QLabel(
            "External tool conversions run during Execute Sort when conversion rules are enabled. "
            "Configure tool paths & templates in config as needed."
        )
        tools_intro.setWordWrap(True)
        tools_layout.insertWidget(0, tools_intro)

        output_edit = DropLineEdit(on_drop_output, parent_widget, enabled=dnd_enabled)
        temp_edit = DropLineEdit(on_drop_temp, parent_widget, enabled=dnd_enabled)
        output_edit.setPlaceholderText("Optional output folder for external tool results")
        temp_edit.setPlaceholderText("Optional temp folder for external tool processing")

        btn_output = QtWidgets.QPushButton("Select Output…")
        btn_temp = QtWidgets.QPushButton("Select Temp…")
        btn_output.setMinimumWidth(150)
        btn_temp.setMinimumWidth(150)

        external_form.addWidget(QtWidgets.QLabel("Output:"), 0, 0)
        external_form.addWidget(output_edit, 0, 1)
        external_form.addWidget(btn_output, 0, 2)
        external_form.addWidget(QtWidgets.QLabel("Temp:"), 1, 0)
        external_form.addWidget(temp_edit, 1, 1)
        external_form.addWidget(btn_temp, 1, 2)
        external_form.setColumnStretch(1, 1)

        tools_layout.addWidget(tools_group)

        tools_hint = QtWidgets.QLabel(
            "Probe results are generated by running each tool with a non-existent input. "
            "This confirms the executable responds without guessing flags."
        )
        tools_hint.setWordWrap(True)
        tools_layout.addWidget(tools_hint)

    return ExternalToolsUI(
        tools_group=tools_group,
        tools_status_hint=tools_status_hint,
        wud2app_version=wud2app_version,
        wud2app_probe=wud2app_probe,
        wudcompress_version=wudcompress_version,
        wudcompress_probe=wudcompress_probe,
        btn_tools_probe=btn_tools_probe,
        output_edit=output_edit,
        temp_edit=temp_edit,
        btn_output=btn_output,
        btn_temp=btn_temp,
    )
